# Generated by Django 4.0.3 on 2023-01-19 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('menugroup1', models.CharField(max_length=100)),
                ('menugroup2', models.CharField(max_length=100)),
                ('menugroup3', models.CharField(max_length=100)),
                ('menugroup4', models.CharField(max_length=100)),
                ('tc', models.BooleanField()),
                ('note', models.CharField(max_length=100)),
                ('gprname', models.CharField(max_length=100)),
                ('seque', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_customer', models.BooleanField(default=True)),
                ('is_vendor', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FieldMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldmas', models.CharField(max_length=50)),
                ('placeholdermsg', models.CharField(max_length=100)),
                ('errormsg', models.CharField(max_length=100)),
                ('inactivefield', models.BooleanField()),
                ('notefield', models.CharField(max_length=50)),
                ('lastupdateuserfield', models.CharField(max_length=50)),
                ('lastupdatedatefield', models.DateField(auto_now=True)),
                ('lastupdatetimefield', models.TimeField(auto_now=True)),
                ('lastupdatetaskfield', models.CharField(max_length=50)),
                ('lastupdateipfield', models.CharField(max_length=120)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grpname', models.CharField(max_length=120)),
                ('sequence', models.CharField(max_length=100)),
                ('inactive', models.BooleanField()),
                ('note', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuname', models.CharField(max_length=20)),
                ('taskname', models.CharField(max_length=20)),
                ('groupname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.menugroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.PositiveBigIntegerField(choices=[(1, 'Administrator'), (2, 'normal_user'), (3, 'Customer'), (4, 'Vendor')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst', models.CharField(max_length=34)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTaskAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactivetaskacc', models.BooleanField()),
                ('notetaskacc', models.CharField(max_length=50)),
                ('viewaccess', models.BooleanField()),
                ('addaccess', models.BooleanField()),
                ('editaccess', models.BooleanField()),
                ('deleteaccess', models.BooleanField()),
                ('inactiveaccess', models.BooleanField()),
                ('lastupdateuseracc', models.CharField(max_length=50)),
                ('lastupdatedateacc', models.DateField(auto_now=True)),
                ('lastupdatetimeacc', models.TimeField(auto_now=True)),
                ('lastupdatetaskacc', models.CharField(max_length=50)),
                ('lastupdateipacc', models.CharField(max_length=20)),
                ('taskacc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.menumaster')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('f_msg1', models.TextField()),
                ('f_msg2', models.TextField()),
                ('f_note', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Save Draft'), ('published', 'Published')], max_length=20)),
                ('task', models.CharField(max_length=180)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('pyname', models.CharField(max_length=30)),
                ('inactivetask', models.BooleanField()),
                ('notetask', models.CharField(max_length=50)),
                ('lastupdatedate', models.DateField(auto_now=True)),
                ('lastupdatetime', models.TimeField(auto_now=True)),
                ('lastupdatetask', models.CharField(max_length=50)),
                ('lastupdateip', models.CharField(max_length=20)),
                ('lastupdateuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.menumaster')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFieldMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted', models.BooleanField()),
                ('inactivetaskfield', models.BooleanField()),
                ('notetaskfield', models.CharField(max_length=50)),
                ('lastupdateusertaskfield', models.CharField(max_length=50)),
                ('lastupdatedatetaskfield', models.DateField(auto_now=True)),
                ('lastupdatetimetaskfield', models.TimeField(auto_now=True)),
                ('lastupdatetasktaskfield', models.CharField(max_length=50)),
                ('lastupdateiptaskfield', models.CharField(max_length=20)),
                ('company', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('fieldtaskfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.fieldmaster')),
                ('tasktaskfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.menumaster')),
                ('usertaskfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('grpname', models.CharField(max_length=80)),
                ('sequence', models.CharField(max_length=40)),
                ('inactive', models.BooleanField()),
                ('note', models.CharField(max_length=50)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=34)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usertype'),
        ),
    ]
